import = [
#     "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[window]
decorations="None"
startup_mode="Fullscreen"
dynamic_padding=true

[scrolling]
history=100000

[font]
normal={family="FiraCode Nerd Font"}
size=15

[shell]
# program="zellij"
# args=["attach", "--create"]
program="tmux"
